name: Build artifacts

on:
  workflow_dispatch:
  push:
    branches:
    - master
  pull_request:

permissions:
  id-token: write

jobs:
  build:
    name: Build artifacts
    runs-on: ubuntu-26.04-arm
    steps:
    - uses: actions/checkout@main
    - uses: NixOS/nix-installer-action@main
    - uses: Mic92/niks3-action@main
      with:
        server-url: https://niks3.usertam.dev
    - name: Build userland archive
      run: |
        nix build --print-build-logs --keep-going --fallback \
          .#packages.aarch64-linux.archive.userland
        echo "USERLAND_ARCHIVE_NAME=$(basename result/remarkable2-userland-*.tar.xz .tar.xz)" >> $GITHUB_ENV
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ env.USERLAND_ARCHIVE_NAME }}
        path: result/remarkable2-userland-*.tar.xz
    - name: Build kernel archive
      run: |
        nix build --print-build-logs --keep-going --fallback \
          .#packages.aarch64-linux.archive.kernel
        echo "KERNEL_ARCHIVE_NAME=$(basename result/remarkable2-kernel-*.tar.xz .tar.xz)" >> $GITHUB_ENV
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ env.KERNEL_ARCHIVE_NAME }}
        path: result/remarkable2-kernel-*.tar.xz
