name: "Build artifacts"

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04-arm
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Build userland archive
      run: |
        nix build .#packages.aarch64-linux.archive.userland --print-build-logs --keep-going
        cp -a result/tarball/remarkable2-userland-*.tar.xz .
    - uses: actions/upload-artifact@v4
      with:
        name: remarkable2-userland-archive
        path: remarkable2-userland-*.tar.xz
    - name: Build kernel archive
      run: |
        nix build .#packages.aarch64-linux.archive.kernel --print-build-logs --keep-going
        cp -a result/tarball/remarkable2-kernel-*.tar.xz .
    - uses: actions/upload-artifact@v4
      with:
        name: remarkable2-kernel-archive
        path: remarkable2-kernel-*.tar.xz
